image: node:latest

stages:
  - install_dependencies
  - check_code
  - build

cache:
  paths:
    - node_modules/

install:
  stage: install_dependencies
  script:
    - npm install
  artifacts:
    paths:
    - node_modules/

lint:
  stage: check_code
  script: 
    - npm run-script lint
  needs: ["install"]

test:
  stage: check_code
  script: 
    - npm run-script test
  needs: ["install", "lint"] 

coverage:
  stage: check_code
  script: 
    - npm run-script coverage
  needs: ["install", "lint", "test"]

build:
  stage: build
  script: 
    - npm run-script build

